version: '3.3'

services:
  streamlit:
    build: streamlit
    image: an0101st/mds_dsc_text_gen
    ports:
      - 80:${STREAMLIT_SERVER_PORT:-80}
    environment:
      - STREAMLIT_SERVER_PORT=${STREAMLIT_SERVER_PORT:-80}